---
- name: set config for sensu client.
  template: src={{ item }}.j2 dest=/etc/sensu/conf.d/{{ item }}
  with_items:
    - rabbitmq.json
    - client.json
 
- name: install modules.
  yum: name={{ item }} state=installed
  with_items:
    - ruby
    - rubygems
    - ruby-devel

- name: install sensu-plugin of gem.
  command: sudo gem install sensu-plugin --no-rdoc --no-ri

- name: install wget modules.
  yum: name={{ item }} state=installed
  with_items:
    - wget

- name: get sample proc check script.
  command: sudo wget -O /etc/sensu/plugins/check-procs.rb https://raw.github.com/sensu/sensu-community-plugins/master/plugins/processes/check-procs.rb

- name: set stat for sample proc check script.
  file: path=/etc/sensu/plugins/check-procs.rb owner=sensu group=sensu mode=0755

- name: start sensu client.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sensu-client

