---
- name: check rabbitmq vhost for sensu.
  shell: rabbitmqctl list_users | grep {{ rabbitmq_sensu_user }}
  register: result
  ignore_errors: True

- name: create a rabbitmq vhost for sensu.
  command: rabbitmqctl add_vhost /sensu
  when: result|failed

- name: create a rabbitmq user for sensu.
  command: rabbitmqctl add_user {{ rabbitmq_sensu_user }} {{ rabbitmq_sensu_pass }}
  when: result|failed

- name: set a rabbitmq vhost permition for sensu.
  command: rabbitmqctl set_permissions -p /sensu {{ rabbitmq_sensu_user }} ".*" ".*" ".*"
  when: result|failed

- name: install uchiwa.
  yum: name=uchiwa state=installed

- name: set config for sensu server.
  template: src={{ item }}.j2 dest=/etc/sensu/conf.d/{{ item }}
  with_items:
    - rabbitmq.json
    - redis.json
    - api.json
    - client.json
    - check_cron.json

- name: start sensu server/api.
  service: name={{ item }} state=started enabled=yes
  with_items:
    - sensu-server
    - sensu-api

- name: set config for uchiwa (sensu dashboard).
  template: src={{ item }}.j2 dest=/etc/sensu/{{ item }}
  with_items:
    - uchiwa.json

- name: start uchiwa (sensu dashboard).
  service: name={{ item }} state=started enabled=yes
  with_items:
    - uchiwa

